apiVersion: v1
kind: Secret
metadata:
  name: tasksphere-secrets
  namespace: tasksphere
  labels:
    app.kubernetes.io/part-of: tasksphere
type: Opaque
data:
  JWT_SECRET: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="      # change-me-in-production
  DB_PASSWORD: "Y2hhbmdlbWU="                             # changeme
  MINIO_ACCESS_KEY: "bWluaW9hZG1pbg=="                    # minioadmin
  MINIO_SECRET_KEY: "bWluaW9hZG1pbg=="                    # minioadmin
