apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tasksphere-secrets
  namespace: tasksphere-dev
  labels:
    app.kubernetes.io/part-of: tasksphere-pro
    app.kubernetes.io/managed-by: dapr
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
  scopes:
    - auth-service
    - project-service
    - task-service
    - file-service
    - notification-service
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tasksphere-secrets-access
  namespace: tasksphere-dev
spec:
  secrets:
    scopes:
      - storeName: tasksphere-secrets
        defaultAccess: deny
        allowedSecrets:
          - postgres-secret
          - kafka-secret
          - jwt-signing-key
          - minio-credentials
          - email-api-key
