input {
  tcp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  if [trace_id] {
    mutate {
      add_field => { "[@metadata][index_suffix]" => "traces" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index_suffix]" => "logs" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orchestration-%{[@metadata][index_suffix]}-%{+YYYY.MM.dd}"
  }
}
